### ISSUE TITLE
Allow setting channel priority

### ISSUE THREAD

**Issue by awvwgk** [mamba-org/provision-with-micromamba#33]
The channel priority is currently set by default to *strict* at

https://github.com/mamba-org/provision-with-micromamba/blob/a2be56c595b5dc528dbbeba1083f57b99d915554/index.js#L61

However, not all environments necessarily solve with *strict* channel priority. For those environments it would be useful to allow adjusting the channel priority to *flexible*.

**Comment by wwarriner** [comment]
Our project would benefit from this. We are using mamba in our CI for building our documentation. I had channels listed alphabetically (anaconda > conda-forge), which caused `markdown=3.3.4` to be used instead of `markdown=3.3.7`, causing our fenced code blocks to render improperly. I was able to work around strict priority by flipping the order of channels. However, it isn't clear if this won't come up again as package dependencies and versions change.

Could we please have a `channel_priority: flexible` option?

**Comment by jonashaag** [comment]
PR welcome, shouldn’t be too difficult. 

You may also want to pin the markdown package
